import './global.css';
import { Providers } from "@/app/providers";
import Layout from "@/layout";
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'
import {getConfig} from "@/wagmi";

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get('cookie'),
  )
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background">
        <Providers initialState={initialState}>
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
